# Generated by Django 5.1.4 on 2025-02-18 17:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_buyer_remove_user_is_farmer_user_role_and_more'),
    ]

    operations = [
         migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
