# Generated by Django 5.1.4 on 2025-02-24 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_farmerprofile_lat_alter_farmerprofile_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('rubber', 'Rubber'), ('coconut', 'Coconut'), ('jackfruit', 'Jackfruit'), ('banana', 'Banana'), ('pepper', 'Black Pepper'), ('cardamom', 'Cardamom'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('arecanut', 'Arecanut'), ('cashew', 'Cashew'), ('ginger', 'Ginger'), ('turmeric', 'Turmeric'), ('nutmeg', 'Nutmeg'), ('clove', 'Clove'), ('tapioca', 'Tapioca'), ('mango', 'Mango'), ('pineapple', 'Pineapple'), ('others', 'Others')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
