# Generated by Django 5.1.4 on 2025-03-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phoneno', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
