# Generated by Django 5.1.4 on 2025-03-19 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_deliver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('count', 'Count/Pieces'), ('dozen', 'Dozen'), ('lb', 'Pound'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('bundle', 'Bundle')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
