# Generated by Django 5.1.4 on 2025-03-20 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rubber', 'Rubber'), ('coconut', 'Coconut'), ('jackfruit', 'Jackfruit'), ('banana', 'Banana'), ('pepper', 'Black Pepper'), ('cardamom', 'Cardamom'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('arecanut', 'Arecanut'), ('cashew', 'Cashew'), ('ginger', 'Ginger'), ('turmeric', 'Turmeric'), ('nutmeg', 'Nutmeg'), ('clove', 'Clove'), ('tapioca', 'Tapioca'), ('mango', 'Mango'), ('pineapple', 'Pineapple'), ('others', 'Others')], max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('count', 'Count/Pieces'), ('dozen', 'Dozen'), ('lb', 'Pound'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('bundle', 'Bundle')], max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
