# Generated by Django 5.1.4 on 2025-03-21 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DemandResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, help_text="Farmer's offered price per unit", max_digits=10)),
                ('offered_quantity', models.DecimalField(decimal_places=2, help_text='Quantity the farmer can provide', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional details or terms from the farmer', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.demand')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('demand', 'farmer')},
            },
        ),
    ]
