# Generated by Django 5.1.4 on 2025-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_demand_buyer_demandresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandresponse',
            name='buyer_message',
            field=models.TextField(blank=True, help_text='Message from buyer when accepting the response', null=True),
        ),
    ]
