# Generated by Django 5.1.4 on 2025-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_demandresponse_buyer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
