# Generated by Django 5.1.4 on 2025-03-31 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notification_chat_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_ratings', to=settings.AUTH_USER_MODEL)),
                ('rated_by', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='rated_buyers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('buyer', 'rated_by')},
            },
        ),
        migrations.CreateModel(
            name='FarmerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_ratings', to=settings.AUTH_USER_MODEL)),
                ('rated_by', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='rated_farmers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('farmer', 'rated_by')},
            },
        ),
    ]
