# Generated by Django 5.1.4 on 2025-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandresponse',
            name='break_requested',
            field=models.BooleanField(default=False, help_text='Whether a break has been requested for this deal'),
        ),
        migrations.AddField(
            model_name='demandresponse',
            name='break_requested_by',
            field=models.CharField(blank=True, help_text='Who requested to break the deal (farmer/buyer)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='break_requested',
            field=models.BooleanField(default=False, help_text='Whether a break has been requested for this deal'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='break_requested_by',
            field=models.CharField(blank=True, help_text='Who requested to break the deal (farmer/buyer)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demandresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('demand_response', 'Demand Response'), ('response_accepted', 'Response Accepted'), ('response_rejected', 'Response Rejected'), ('product_offer', 'Product Offer'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('delivery_status', 'Delivery Status Update'), ('message', 'Message'), ('system', 'System Notification'), ('break_request', 'Break Deal Request'), ('deal_canceled', 'Deal Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
