# Generated by Django 5.1.4 on 2025-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_demandresponse_break_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandresponse',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether payment has been completed for this deal'),
        ),
        migrations.AddField(
            model_name='demandresponse',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='demandresponse',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether payment has been completed for this deal'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID', max_length=100, null=True),
        ),
    ]
