# Generated by Django 5.1.4 on 2025-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_demandresponse_is_paid_demandresponse_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandresponse',
            name='complete_requested',
            field=models.BooleanField(default=False, help_text='Whether completion has been requested for this deal'),
        ),
        migrations.AddField(
            model_name='demandresponse',
            name='complete_requested_by',
            field=models.CharField(blank=True, help_text='Who requested to complete the deal (farmer/buyer)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='complete_requested',
            field=models.BooleanField(default=False, help_text='Whether completion has been requested for this deal'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='complete_requested_by',
            field=models.CharField(blank=True, help_text='Who requested to complete the deal (farmer/buyer)', max_length=10, null=True),
        ),
    ]
